### ISSUE TITLE
[Question] Binary body

### ISSUE THREAD

**Issue by SilenLoc** [ethancarlsson/openapi-to-hurl#6]
Hey, thank you very much for this tooling.

It works very well. 

I have a question regarding generating bodies.
Maybe I missed something but:

is it possible to let the tool create a hurl file like this:

```hurl
POST {{host}}/file/{{some_hurl_var}}
Content-Type: {{Content-Type}}
file,testfiles/good_pdf.pdf;

HTTP *
[Asserts]
status < 400
```

I managed to create:

```hurl
POST {{host}}/file/string_value
Content-Type: {{Content-Type}}

HTTP *
[Asserts]
status < 400
```

**Comment by ethancarlsson** [comment]
Hey, thanks I'm glad you like it.

At the moment it's not possible, but it's a good idea and it would be easy to add.

What do you think about something like `openapi-to-hurl some_spec.json -path-params as-variables`? Where we set the variables to the name of the path param in the spec, so a spec like this
```json
   "/some-endpoint/{someId}": {
      "get": {
        "parameters": [
          {
            "name": "someId",
            "in": "path",
            "required": true,
            "schema": {
              "type": "string"
            }
          }
        ],
...
```
Would produce a hurl file like this
```hurl
GET {{host}}/some-endpoint/{{someId}}
```

**Comment by SilenLoc** [comment]
> Hey, thanks I'm glad you like it.
> 
> At the moment it's not possible, but it's a good idea and it would be easy to add.
> 
> What do you think about something like `openapi-to-hurl some_spec.json -path-params as-variables`? Where we set the variables to the name of the path param in the spec, so a spec like this
> 
> ```json
>    "/some-endpoint/{someId}": {
>       "get": {
>         "parameters": [
>           {
>             "name": "someId",
>             "in": "path",
>             "required": true,
>             "schema": {
>               "type": "string"
>             }
>           }
>         ],
> ...
> ```
> 
> Would produce a hurl file like this
> 
> ```
> GET {{host}}/some-endpoint/{{someId}}
> ```

Yes that would be my expectation when reading the spec. However, the name space can be a problem. As global variables it would be bad to get "{{id}}". Maybe it would not be a global variable? But more like this in the options of the relevant file:

```hurl
[Options]
variable: country=Italy # define variable country
variable: planet=Earth  
```

**Comment by ethancarlsson** [comment]
Yeah, that seems like a really good use of `[Options]`.  We can set it up so that `openapi-to-hurl some_spec.json --path-params variables` produces

```hurl
GET {{host}}/some-endpoint/{{someId}}
[Options]
variable: someId=string_value # This can be set to something different by setting an example in the spec
```

**Comment by ethancarlsson** [comment]
[In v1.2.0](https://github.com/ethancarlsson/openapi-to-hurl/releases/tag/v1.2.0) you can now set the path params via variables in option using`hurl some_spec.json --path-params variables`. Thanks for your input on this!
